[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mirrorshift"
version = "0.1.0"
description = "my personal repo for transformers implementations and experiments"
requires-python = ">=3.11"
dependencies = [
    "torch==2.7.1",
    "tyro>=0.9.35",
    "wandb>=0.21.1",
    "mirrordata",
]

[dependency-groups]
dev = ["pytest>=8.3.4"]

[tool.setuptools.packages.find]
include = ["mirrorshift*"]

[tool.uv.workspace]
members = [
    "mirrordata",
]

[tool.uv.sources]
mirrordata = { workspace = true }

[project.scripts]
mirrorshift-train = "mirrorshift.train:main"
