[pytest]
testpaths = tests
filterwarnings =
    ignore:Failed to initialize NumPy:UserWarning
    ignore:torch.distributed is disabled, unavailable or uninitialized, assuming the intent is to save in a single process.:UserWarning
    ignore:torch.distributed is disabled, unavailable or uninitialized, assuming the intent is to load in a single process.:UserWarning
    ignore:TypedStorage is deprecated:UserWarning
